#!/bin/sh

monitors=$(bspc query -M --names)
primary=$(bspc query -M -m primary --names)
monitor_count=$(echo $monitors|wc -w)

if [[ $monitor_count -eq 1 ]]; then
    bspc monitor $monitor -d 1 2 3 4 5 6 7 8 9 0
elif [[ $monitor_count -eq 2 ]]; then
    for monitor in $monitors; do
        if [[ "$monitor" == "$primary" ]]; then
            bspc monitor $monitor -d 1 2 3 4 5 6 7
            echo 1
        else
            bspc monitor $monitor -d 8 9 0
            echo 2
        fi
    done
fi

bspc config border_width                0
bspc config window_gap                  12

bspc config split_ratio                 0.5
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config single_monocle              true
bspc config focus_follows_pointer       true
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true
bspc config merge_overlapping_monitors  true
bspc config honor_size_hints            false

bspc rule -a Gimp state=floating follow=on
bspc rule -a URxvt:mixer state=floating
bspc rule -a URxvt:bashrun state=floating

[[ ! $(pgrep polybar) ]] && polybar mybar &
